// Auto-generated by lara-bun build-rsc — do not edit
import { renderToReadableStream } from "react-server-dom-webpack/server.edge";
import { createElement } from "react";




export async function resolveMetadata(): Promise<null> {
  return null;
}

interface LayoutEntry {
  component: string;
  props: Record<string, unknown>;
}

const components: Record<string, React.ComponentType<any>> = {

};

function buildElement(
  component: string,
  props: Record<string, unknown>,
  layouts: LayoutEntry[]
): React.ReactElement {
  const Component = components[component];

  if (!Component) {
    throw new Error(
      `Unknown RSC component: "${component}". Available: ${Object.keys(components).join(", ")}`
    );
  }

  let element = createElement(Component, props);

  // Wrap in layouts: layouts[0] is outermost, layouts[last] is innermost
  for (let i = layouts.length - 1; i >= 0; i--) {
    const Layout = components[layouts[i].component];
    if (!Layout) {
      throw new Error(
        `Unknown layout component: "${layouts[i].component}". Available: ${Object.keys(components).join(", ")}`
      );
    }
    element = createElement(Layout, { ...layouts[i].props, children: element });
  }

  return element;
}

export async function renderRsc(
  component: string,
  props: Record<string, unknown>,
  clientManifest: Record<string, unknown>,
  layouts: LayoutEntry[] = []
): Promise<string> {
  const element = buildElement(component, props, layouts);
  const stream = renderToReadableStream(element, clientManifest);

  return await new Response(stream).text();
}

export function renderRscStream(
  component: string,
  props: Record<string, unknown>,
  clientManifest: Record<string, unknown>,
  layouts: LayoutEntry[] = []
): ReadableStream {
  const element = buildElement(component, props, layouts);
  return renderToReadableStream(element, clientManifest);
}
