// CLI behind `php artisan rsc:build`.
//
// The build itself lives in the Vite plugin (resources/vite.ts). This only
// decides which config Vite runs: the app's own vite.rsc.config if it has one,
// otherwise a minimal generated config that just uses the plugin. Either way
// Vite runs that config directly — nothing is merged on top of it.

import { existsSync, mkdirSync, writeFileSync } from 'node:fs'
import { join, resolve } from 'node:path'

const projectRoot = resolve(process.env.LARA_BUN_PROJECT_ROOT || process.cwd())
const outDir = resolve(process.env.BUN_RSC_OUT_DIR || join(projectRoot, 'bootstrap/rsc/vite'))
const genDir = join(outDir, '.gen')

function log(...args: unknown[]): void {
  console.error('[lara-bun:vite]', ...args)
}

export const USER_CONFIG_NAMES = [
  'vite.rsc.config.ts',
  'vite.rsc.config.mts',
  'vite.rsc.config.js',
  'vite.rsc.config.mjs',
] as const

/**
 * Find the app's own Vite config for the RSC build, if it has one.
 *
 * Anything an app wants in this build — the React Compiler, Tailwind, extra
 * aliases — is declared there. The engine takes no view on which plugins an
 * app should use and detects nothing.
 */
export function findUserViteConfig(root: string): string | null {
  const explicit = process.env.BUN_RSC_VITE_CONFIG

  if (explicit) {
    const path = resolve(explicit)

    return existsSync(path) ? path : null
  }

  for (const name of USER_CONFIG_NAMES) {
    const path = join(root, name)
    if (existsSync(path)) return path
  }

  return null
}

/**
 * Write the fallback config used when the app has none of its own — the plugin
 * and nothing else, so a project works without a Vite config to maintain.
 */
export function writeDefaultConfig(pluginPath: string, target: string): string {
  mkdirSync(genDir, { recursive: true })

  writeFileSync(
    target,
    `// GENERATED by build-rsc-vite.ts — do not edit.
// Add a vite.rsc.config.ts to your project root to take this over.
import { rscRoutes } from ${JSON.stringify(pluginPath)}
import { defineConfig } from 'vite'

export default defineConfig({ plugins: [rscRoutes()] })
`,
  )

  return target
}

function main(): void {
  const userConfig = findUserViteConfig(projectRoot)
  let configPath: string

  if (userConfig) {
    log(`Using app Vite config: ${userConfig}`)
    configPath = userConfig
  } else {
    configPath = writeDefaultConfig(join(import.meta.dir, 'vite.ts'), join(genDir, 'vite.config.mjs'))
  }

  const watch = process.env.BUN_RSC_WATCH === '1'
  const viteArgs = [process.execPath, 'x', '--bun', 'vite', 'build', '--config', configPath]
  if (watch) viteArgs.push('--watch')

  log(`Running vite build${watch ? ' --watch' : ''}...`)

  const proc = Bun.spawnSync(viteArgs, {
    cwd: projectRoot,
    env: {
      ...process.env,
      NODE_ENV: watch ? 'development' : 'production',
      // Vite stages the config through node_modules/.vite-temp, so the plugin
      // cannot locate this package from its own import.meta. Pass it through.
      LARA_BUN_PACKAGE_DIR: import.meta.dir,
    },
    stdout: 'inherit',
    stderr: 'inherit',
  })

  if (proc.exitCode !== 0) {
    log('vite build failed')
    process.exit(proc.exitCode ?? 1)
  }

  log(`Build complete → ${join(outDir, 'dist')}`)
}

if (import.meta.main) {
  main()
}
