// CLI behind `php artisan rsc:build`.
//
// The build itself lives in the Vite plugin (resources/vite.ts). This only
// decides which config Vite runs: the app's own vite.rsc.config if it has one,
// otherwise a minimal generated config that just uses the plugin. Either way
// Vite runs that config directly — nothing is merged on top of it.

import { spawnSync } from 'node:child_process'
import { existsSync, mkdirSync, writeFileSync } from 'node:fs'
import { dirname, join, resolve } from 'node:path'
import { isBun } from './runtime.ts'

const projectRoot = resolve(process.env.RSC_PROJECT_ROOT || process.cwd())
const outDir = resolve(process.env.RSC_OUT_DIR || join(projectRoot, 'bootstrap/rsc/vite'))

function log(...args: unknown[]): void {
  console.error('[laravel-rsc]', ...args)
}

export const USER_CONFIG_NAMES = [
  'vite.rsc.config.ts',
  'vite.rsc.config.mts',
  'vite.rsc.config.js',
  'vite.rsc.config.mjs',
] as const

/**
 * Find the app's own Vite config for the RSC build, if it has one.
 *
 * Anything an app wants in this build — the React Compiler, Tailwind, extra
 * aliases — is declared there. The engine takes no view on which plugins an
 * app should use and detects nothing.
 */
export function findUserViteConfig(root: string): string | null {
  const explicit = process.env.RSC_VITE_CONFIG

  if (explicit) {
    const path = resolve(explicit)

    return existsSync(path) ? path : null
  }

  for (const name of USER_CONFIG_NAMES) {
    const path = join(root, name)
    if (existsSync(path)) return path
  }

  return null
}

/**
 * Write the fallback config used when the app has none of its own — the plugin
 * and nothing else, so a project works without a Vite config to maintain.
 */
export function writeDefaultConfig(pluginPath: string, target: string): string {
  mkdirSync(dirname(target), { recursive: true })

  writeFileSync(
    target,
    `// GENERATED by build-rsc-vite.ts — do not edit. Kept on disk so the build
// this project actually runs is inspectable; add a vite.rsc.config.ts to your
// project root to take it over.
import { rscRoutes } from ${JSON.stringify(pluginPath)}
import { defineConfig } from 'vite'

export default defineConfig({ plugins: [rscRoutes()] })
`,
  )

  return target
}

/** This file's directory — import.meta.dir is Bun-only. */
function packageDir(): string {
  return resolve(new URL('.', import.meta.url).pathname)
}

function main(): void {
  const userConfig = findUserViteConfig(projectRoot)
  let configPath: string

  if (userConfig) {
    log(`Using app Vite config: ${userConfig}`)
    configPath = userConfig
  } else {
    configPath = writeDefaultConfig(join(packageDir(), 'vite.ts'), join(outDir, 'vite.config.mjs'))
  }

  const watch = process.env.RSC_WATCH === '1'
  const viteArgs = ['build', '--config', configPath]
  if (watch) viteArgs.push('--watch')

  // Under Bun, `bun x --bun vite` keeps Vite itself on the Bun runtime. Under
  // Node there is no such wrapper, so invoke the locally installed binary.
  const [command, args] = isBun
    ? [process.execPath, ['x', '--bun', 'vite', ...viteArgs]]
    : [join(projectRoot, 'node_modules/.bin/vite'), viteArgs]

  log(`Running vite build${watch ? ' --watch' : ''}...`)

  const proc = spawnSync(command, args, {
    cwd: projectRoot,
    env: {
      ...process.env,
      NODE_ENV: watch ? 'development' : 'production',
      // Vite stages the config through node_modules/.vite-temp, so the plugin
      // cannot locate this package from its own import.meta. Pass it through.
      RSC_PACKAGE_DIR: packageDir(),
    },
    stdio: 'inherit',
  })

  if (proc.status !== 0) {
    log('vite build failed')
    process.exit(proc.status ?? 1)
  }

  log(`Build complete → ${join(outDir, 'dist')}`)
}

// Run only when invoked directly, not when imported for its helpers.
if (process.argv[1] && resolve(process.argv[1]) === resolve(new URL(import.meta.url).pathname)) {
  main()
}
