// GENERATED by build-rsc-vite.ts — do not edit. Kept on disk so the build
// this project actually runs is inspectable; add a vite.rsc.config.ts to your
// project root to take it over.
import { rscRoutes } from "/Users/ramonmalcolm/Herd/lara-bun/resources/vite.ts"
import { defineConfig } from 'vite'

export default defineConfig({ plugins: [rscRoutes()] })
