// GENERATED by rscRoutes() — do not edit.
import { renderToReadableStream, decodeReply, loadServerAction } from '@vitejs/plugin-rsc/rsc'
import { Suspense, createElement, Fragment } from 'react'
import _c_app_page from "/var/folders/zg/p8mb4gyj5n581zcrhgvd_ck80000gn/T/larabun-icpt-MtbTcA/app/page.tsx"
import _c_app_layout from "/var/folders/zg/p8mb4gyj5n581zcrhgvd_ck80000gn/T/larabun-icpt-MtbTcA/app/layout.tsx"

type HostFn = (name: string, ...args: unknown[]) => Promise<unknown>
type LayoutEntry = { component: string; props?: Record<string, unknown> }
type SlotOverride = { component: string; props?: Record<string, unknown> }

const components: Record<string, any> = {
  "app/page": _c_app_page,
  "app/layout": _c_app_layout,
}

const metadataMap: Record<string, { static?: any; generate?: (p: any) => any }> = {

}

// The host installs its callable via installHostFn. The global must be set
// synchronously INSIDE each render fn (applyHost) right before
// renderToReadableStream — setting it once ahead of a separate render call does
// not reach the Flight render.
const HOST_GLOBAL = "rpc"

let currentHost: HostFn | null = null

export function installHostFn(fn: HostFn) {
  currentHost = fn
  return () => {
    if (currentHost === fn) currentHost = null
  }
}

function applyHost() {
  ;(globalThis as Record<string, unknown>)[HOST_GLOBAL] = currentHost
}

// Composition: layout(outer..inner) > Suspense(loading, innermost-first) > page.
function buildElement(
  component: string,
  props: Record<string, unknown>,
  layouts: LayoutEntry[],
  loadings: string[],
  parallelSlots: Record<string, string>,
  slotOverrides: Record<string, SlotOverride>,
  head: unknown[] = [],
) {
  const Component = components[component]
  if (!Component) throw new Error('Unknown RSC component: ' + component)

  let element = createElement(Component, props)

  for (let i = loadings.length - 1; i >= 0; i--) {
    const Loading = components[loadings[i]]
    element = createElement(Suspense, { fallback: Loading ? createElement(Loading) : null }, element)
  }

  // <title>/<meta> go OUTSIDE the Suspense boundaries so they reach the shell
  // immediately — inside, they would be withheld until the page's data
  // resolves, delaying the whole document on a slow page.
  if (head.length) element = createElement(Fragment, null, ...head, element)

  const slotElements: Record<string, unknown> = {}
  for (const [slot, value] of Object.entries(parallelSlots)) {
    const override = slotOverrides[slot]
    if (override) {
      const OverrideComp = components[override.component]
      slotElements[slot] = OverrideComp ? createElement(OverrideComp, override.props ?? {}) : null
    } else {
      const SlotComp = components[value]
      slotElements[slot] = SlotComp ? createElement(SlotComp, props) : null
    }
  }

  for (let i = layouts.length - 1; i >= 0; i--) {
    const Layout = components[layouts[i].component]
    if (!Layout) continue
    const layoutProps = { ...(layouts[i].props ?? {}) }
    if (i === layouts.length - 1) {
      element = createElement(Layout, { ...layoutProps, ...slotElements, children: element })
    } else {
      element = createElement(Layout, { ...layoutProps, children: element })
    }
  }

  return element
}

// Resolve route metadata into React elements. React 19 hoists <title>/<meta>
// rendered anywhere in the tree into <head> — so the "vite way" for metadata is
// to render it as elements, no PHP-side <head> string injection.
async function renderTree(
  component: string,
  props: Record<string, unknown>,
  layouts: LayoutEntry[],
  loadings: string[],
  parallelSlots: Record<string, string>,
  slotOverrides: Record<string, SlotOverride>,
) {
  const md = await resolveMetadata(component, props, layouts)
  const head: unknown[] = []

  if (md) {
    if (md.title != null) head.push(createElement('title', { key: '__t' }, String(md.title)))
    if (md.description != null) head.push(createElement('meta', { key: '__d', name: 'description', content: String(md.description) }))
    for (const [k, v] of Object.entries(md)) {
      if (k === 'title' || k === 'description' || v == null) continue
      head.push(createElement('meta', { key: '__m_' + k, name: k, content: String(v) }))
    }
  }

  // Metadata elements are rendered INSIDE the document tree so React 19 hoists
  // <title>/<meta> into <head> (hoisting only works from within the tree).
  return buildElement(component, props, layouts, loadings, parallelSlots, slotOverrides, head)
}

// SPA-navigation Flight stream (worker: rsc-stream).
export async function handleRscStream(
  component: string,
  props: Record<string, unknown> = {},
  layouts: LayoutEntry[] = [],
  loadings: string[] = [],
  parallelSlots: Record<string, string> = {},
  slotOverrides: Record<string, SlotOverride> = {},
): Promise<{ stream: ReadableStream; clientChunks: unknown }> {
  applyHost()
  return {
    stream: renderToReadableStream(await renderTree(component, props, layouts, loadings, parallelSlots, slotOverrides)),
    clientChunks: {},
  }
}

// Initial-load HTML stream + hydration payload (worker: rsc-html-stream).
export async function handleRscHtmlStream(
  component: string,
  props: Record<string, unknown> = {},
  layouts: LayoutEntry[] = [],
  loadings: string[] = [],
  parallelSlots: Record<string, string> = {},
  slotOverrides: Record<string, SlotOverride> = {},
  nonce?: string,
): Promise<{ htmlStream: ReadableStream; rscPayloadPromise: Promise<string>; clientChunks: unknown }> {
  applyHost()
  const flight = renderToReadableStream(await renderTree(component, props, layouts, loadings, parallelSlots, slotOverrides))
  const [forHtml, forPayload] = flight.tee()
  const rscPayloadPromise = new Response(forPayload).text()
  const ssr = await (import.meta as any).viteRsc.loadModule('ssr', 'index')
  const htmlStream = await ssr.handleSsr(forHtml, nonce)
  return { htmlStream, rscPayloadPromise, clientChunks: {} }
}

// Server action (worker: rsc-action).
export async function handleAction(
  actionId: string,
  body: string | FormData,
  contentType = 'text/plain',
): Promise<{ stream: ReadableStream }> {
  applyHost()

  let decodable: string | FormData = body

  // A multipart body reaches us as a latin1 string — PHP base64s the raw bytes
  // over the socket and the worker decodes them byte-for-byte. Rebuild the
  // bytes so FormData parses, or any File argument is lost.
  if (typeof body === 'string' && contentType.includes('multipart/form-data')) {
    const bytes = new Uint8Array(body.length)
    for (let i = 0; i < body.length; i++) bytes[i] = body.charCodeAt(i)
    decodable = await new Response(bytes, { headers: { 'Content-Type': contentType } }).formData()
  }

  const args = (await decodeReply(decodable)) as unknown[]
  const action = await loadServerAction(actionId)
  const result = await (action as (...a: unknown[]) => unknown)(...args)
  return { stream: renderToReadableStream(result) }
}

export async function resolveMetadata(
  component: string,
  props: Record<string, unknown> = {},
  layouts: LayoutEntry[] = [],
): Promise<Record<string, unknown> | null> {
  const pageEntry = metadataMap[component]
  const page: Record<string, unknown> = pageEntry
    ? (pageEntry.generate ? ((await pageEntry.generate(props)) ?? {}) : { ...(pageEntry.static ?? {}) })
    : {}

  // Non-title metadata: layout defaults (outer→inner), page overrides.
  const merged: Record<string, unknown> = {}
  for (const l of layouts) {
    const s = metadataMap[l.component]?.static
    if (s) for (const [k, v] of Object.entries(s)) if (k !== 'title') merged[k] = v
  }
  for (const [k, v] of Object.entries(page)) if (k !== 'title') merged[k] = v

  // Title: the page title with the NEAREST layout title.template applied; if the
  // page has no title, the nearest layout default/string title.
  let title: string | undefined = typeof page.title === 'string' ? page.title : undefined
  for (let i = layouts.length - 1; i >= 0; i--) {
    const lt = metadataMap[layouts[i].component]?.static?.title as
      | string | { template?: string; default?: string } | undefined
    if (lt && typeof lt === 'object') {
      if (title != null && lt.template) { title = lt.template.replace('%s', title); break }
      if (title == null && lt.default) { title = lt.default; break }
    } else if (title == null && typeof lt === 'string') { title = lt; break }
  }
  if (title != null) merged.title = title

  return Object.keys(merged).length ? merged : null
}

// Buffered render (worker: rsc / rscWithoutCallbacks — used at prerender time).
export async function handleRsc(
  component: string,
  props: Record<string, unknown> = {},
  _callbackSocket: string | null = null,
  layouts: LayoutEntry[] = [],
  loadings: string[] = [],
  parallelSlots: Record<string, string> = {},
): Promise<{ body: string; rscPayload: string; clientChunks: unknown; usedDynamicApis: boolean }> {
  applyHost()
  // renderTree (not bare buildElement) so the prerendered Flight payload carries
  // the same <title>/<meta> elements the live SPA payload does.
  const flight = renderToReadableStream(await renderTree(component, props, layouts, loadings, parallelSlots, {}))
  const [forHtml, forPayload] = flight.tee()
  const rscPayload = await new Response(forPayload).text()
  const ssr = await (import.meta as any).viteRsc.loadModule('ssr', 'index')
  const htmlStream = await ssr.handleSsr(forHtml)
  const body = await new Response(htmlStream).text()
  return { body, rscPayload, clientChunks: {}, usedDynamicApis: false }
}

// PPR shell + classification (worker: rsc-ppr-shell — build-time).
//
// php() is replaced by a probe that records the call and never resolves, so
// every subtree depending on per-request data stays suspended while everything
// static renders normally. Whatever React has flushed when the deadline passes
// IS the shell: layouts, static markup, and Suspense fallbacks.
//
// The two flags this returns are what the prerender pipeline classifies on:
//   usedDynamicApis — the page touched php(), so it cannot be frozen whole
//   timedOut        — the render never finished, i.e. it is still waiting on
//                     data, so only the shell is safe to cache
// A page that sets neither is genuinely static and can be prerendered fully.
const PPR_SHELL_TIMEOUT_MS = Number(process.env.RSC_PPR_TIMEOUT_MS || 2000)

export async function handleRscPprShell(
  component: string,
  props: Record<string, unknown> = {},
  layouts: LayoutEntry[] = [],
  loadings: string[] = [],
  parallelSlots: Record<string, string> = {},
): Promise<{ shellHtml: string; clientChunks: unknown; timedOut: boolean; usedDynamicApis: boolean; error?: string }> {
  let usedDynamicApis = false
  const realHost = (globalThis as Record<string, unknown>)[HOST_GLOBAL]

  ;(globalThis as Record<string, unknown>)[HOST_GLOBAL] = (..._args: unknown[]) => {
    usedDynamicApis = true
    // Never resolves: the awaiting component suspends and React renders its
    // Suspense fallback into the shell instead of the real content.
    return new Promise(() => {})
  }

  let shellHtml = ''
  let completed = false
  let error: string | undefined
  let cancel: (() => void) | null = null

  const produce = (async () => {
    try {
      const tree = await renderTree(component, props, layouts, loadings, parallelSlots, {})
      const flight = renderToReadableStream(tree)
      const ssr = await (import.meta as any).viteRsc.loadModule('ssr', 'index')
      // Errors here are expected: the render is aborted once the shell is out.
      const htmlStream = await ssr.handleSsr(flight, undefined, () => {})

      const reader = htmlStream.getReader()
      // Cancelling aborts the suspended SSR render, which surfaces React's
      // "render was aborted" both synchronously and as a rejection. Neither is
      // interesting — we already have the shell.
      cancel = () => {
        try {
          const pending = reader.cancel()
          if (pending && typeof pending.catch === 'function') pending.catch(() => {})
        } catch {}
      }
      const decoder = new TextDecoder()

      while (true) {
        const { done, value } = await reader.read()
        if (done) break
        shellHtml += decoder.decode(value, { stream: true })
      }

      completed = true
    } catch (e: any) {
      error = e?.message ?? String(e)
    }
  })()

  await Promise.race([produce, new Promise((r) => setTimeout(r, PPR_SHELL_TIMEOUT_MS))])

  // Release the suspended render; its pending php() promises never settle.
  if (!completed) cancel?.()
  ;(globalThis as Record<string, unknown>)[HOST_GLOBAL] = realHost

  return { shellHtml, clientChunks: {}, timedOut: !completed, usedDynamicApis, error }
}

export default async function handler(): Promise<Response> {
  return new Response('rsc-routes entry', { headers: { 'content-type': 'text/plain' } })
}
