// GENERATED by rscRoutes() — do not edit.
import { createFromReadableStream } from '@vitejs/plugin-rsc/ssr'
import { renderToReadableStream } from 'react-dom/server.edge'

export async function handleSsr(
  rscStream: ReadableStream,
  nonce?: string,
  onError?: (error: unknown) => void,
): Promise<ReadableStream> {
  const root = await createFromReadableStream(rscStream)
  const bootstrapScriptContent = await (import.meta as any).viteRsc.loadBootstrapScriptContent('index')
  // Without an onError handler React rejects each abortable task on its own,
  // and those rejections surface as unhandled — noisy for the PPR shell render,
  // which aborts on purpose once it has the shell.
  return renderToReadableStream(root as any, {
    bootstrapScriptContent,
    nonce,
    onError: onError ?? ((error: unknown) => { console.error('[rsc-routes:ssr]', error) }),
  })
}
